// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSZyb47780WqEFyps-DruFxrbGBytR1g',
    appId: '1:858727164441:web:439df49d1c85f3ab079888',
    messagingSenderId: '858727164441',
    projectId: 'pharmaco-a4f66',
    authDomain: 'pharmaco-a4f66.firebaseapp.com',
    databaseURL: 'https://pharmaco-a4f66-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaco-a4f66.appspot.com',
    measurementId: 'G-7LQG03E7VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWaB62GmG2oAlgl2H0kre-064c1i-CKqQ',
    appId: '1:858727164441:android:c04fe962db2ee256079888',
    messagingSenderId: '858727164441',
    projectId: 'pharmaco-a4f66',
    databaseURL: 'https://pharmaco-a4f66-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaco-a4f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsvgLcPPOmMjGyNV6-DdTDS976RREyv2c',
    appId: '1:858727164441:ios:22ba7571ef92cfa9079888',
    messagingSenderId: '858727164441',
    projectId: 'pharmaco-a4f66',
    databaseURL: 'https://pharmaco-a4f66-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaco-a4f66.appspot.com',
    iosBundleId: 'com.example.pharmaco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsvgLcPPOmMjGyNV6-DdTDS976RREyv2c',
    appId: '1:858727164441:ios:8a01c795c5a491a3079888',
    messagingSenderId: '858727164441',
    projectId: 'pharmaco-a4f66',
    databaseURL: 'https://pharmaco-a4f66-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaco-a4f66.appspot.com',
    iosBundleId: 'com.example.pharmaco.RunnerTests',
  );
}
